apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts 
    targetRevision: 18.2.2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx
  syncPolicy:
    automated:
      selfHeal: true
